accounts/urls.py
from django.urls import path

from .views import create_user, login_user, logout_view

app_name = 'accounts'

urlpatterns = [
    path('creation/', create_user, name='create'),
    path('login/', login_user, name='login'),
    path('logout/', logout_view, name='logout'),
]

blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path , include

urlpatterns = [
    path('account/',include('accounts.urls')),
    path('',include('Articles.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':"votre prenom"}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder':"votre nom "}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':"votre nom d'utilisateur"}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder':"votre Email"}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':"votre mot de pass"}),
        }


class UserLoginForm(forms.Form):
    username = forms.CharField(required=True, max_length=50, min_length=3 ,  widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':"votre nom d'utilisateur"}))
    password = forms.CharField(required=True, max_length=50, min_length=3 , widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder':'votre mot de pass'}))

   

   

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import redirect


from .forms import UserForm, UserLoginForm


def create_user(request):
    if request.user.is_authenticated:
        return redirect('List_articles')
    if request.method == 'GET':
        form = UserForm()
    elif request.method == 'POST':
        form = UserForm(data=request.POST)
        if form.is_valid():
            cleaned_data = form.cleaned_data
            user = User.objects.create_user(
                username=cleaned_data.get('username'),
                email=cleaned_data.get('email'),
                password=cleaned_data.get('password')
            )
            user.first_name = cleaned_data.get('first_name')
            user.last_name = cleaned_data.get('last_name')
            user.save()
            return redirect('List_articles')
    data = {
        'form': form
    }
    return render(
        context=data, request=request, template_name='accounts/creation.html'
        )


def login_user(request):
    if request.user.is_authenticated:
        return redirect('List_articles')
    if request.method == "GET":
        form = UserLoginForm()
    elif request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(
                request=request, username=username, password=password
                )
            if user is not None:
                login(request=request, user=user)
                return redirect('List_articles')

    context = {
        'form': form
    }
    return render(request, 'accounts/login.html', context)


def logout_view(request):
    logout(request)
    return redirect('accounts:login')

accounts/templates/accounts/creation.html
{% extends "Articles/Layout.html" %}

{% block content %}
<div class="container-fluid py-5" id="contact">
    <div class="container">
        <div class="position-relative d-flex align-items-center justify-content-center">
            <h1 class="display-1 text-uppercase text-white" style="-webkit-text-stroke: 1px #dee2e6;">Connexion</h1>
            <h1 class="position-absolute text-uppercase text-primary">Creez votre compte</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="contact-form text-center">
                    {% if messages %}
                    <div class="alert alert-success">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <!-- Début du formulaire Django -->
                    <form method="post" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="control-group col-sm-6">
                                <!-- Champ "Votre nom" -->
                                {{ form.first_name.label_tag }}
                                {{ form.first_name }}
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group col-sm-6">
                                <!-- Champ "Email" -->
                                {{ form.last_name.label_tag }}
                                {{ form.last_name}}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="form-row">
                            <div class="control-group col-sm-6">
                                <!-- Champ "Votre nom" -->
                                {{ form.username.label_tag }}
                                {{ form.username }}
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group col-sm-6">
                                <!-- Champ "Email" -->
                                {{ form.email.label_tag }}
                                {{ form.email}}
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group col-sm-12">
                                <!-- Champ "Sujet" -->
                                {{ form.password.label_tag }}
                                {{ form.password }}
                                <p class="help-block text-danger"></p>
                            </div>

                        </div>
                        <div>
                            <input type="submit" value="Envoyer" class="btn btn-info">
                            <input type="reset" value="Annuler" class="btn btn-danger">
                            <p class="mt-4 text-sm text-center">
                                Déjà un compte ? 
                                <a href="{% url 'accounts:login' %}" class="text-primary text-gradient font-weight-bold">Se connecter</a>
                            </p>
                        </div>
                    </form>
                  
                </div>  <!-- Fin du formulaire Django -->
            </div>
        </div>
    </div>
</div>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends "Articles/Layout.html" %}

{% block content %}
<div class="container-fluid py-5" id="contact">
    <div class="container">
        <div class="position-relative d-flex align-items-center justify-content-center">
            <h1 class="display-1 text-uppercase text-white" style="-webkit-text-stroke: 1px #dee2e6;">Connexion</h1>
            <h1 class="position-absolute text-uppercase text-primary">Connectez-vous</h1>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="contact-form text-center">
                    {% if messages %}
                    <div class="alert alert-success">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                    {% endif %}

                    <!-- Début du formulaire Django -->
                    <form method="post" novalidate="novalidate">
                        {% csrf_token %}
                        <div class="form-row">
                            <div class="control-group col-sm-6">
                                <!-- Champ "Votre nom" -->
                                {{ form.username.label_tag }}
                                {{ form.username }}
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group col-sm-6">
                                <!-- Champ "Email" -->
                                {{ form.password.label_tag }}
                                {{ form.password }}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div>
                            <input type="submit" value="Envoyer" class="btn btn-info">
                            <input type="reset" value="Annuler" class="btn btn-danger">
                            <p class="mt-4 text-sm text-center">
                                Vous n'avez pas de compte ? 
                                <a href="{% url 'accounts:create' %}" class="text-primary text-gradient font-weight-bold">Créer un compte</a>
                            </p>
                        </div>
                    </form>
                    <!-- Fin du formulaire Django -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

<!-- <div class="text-center">
    <input type="submit" value="Enregistrer" class="btn btn-info">
    <input type="reset" value="Annuler" class="btn btn-danger">
</div>

<p class="mt-4 text-sm text-center">
    Vous n'avez pas de compte ? 
    <a href="{% url 'accounts:create' %}" class="text-primary text-gradient font-weight-bold">Créer un compte</a>
</p> -->