Articles/urls.py
from django.urls import path 

from .views import home , ArticlesCreateView , ArticlesDeleteView , ArticlesUpdateView , ArticlesListView , ArticlesDetailView , add_comment

urlpatterns = [
    path('detail/<int:pk>/',ArticlesDetailView.as_view(), name='detail_article' ),
    path('update/<int:pk>/',ArticlesUpdateView.as_view(), name='update_article' ),
    path('delete/<int:pk>/',ArticlesDeleteView.as_view(), name='delete_article' ),
    path('form/',ArticlesCreateView.as_view(), name='formulaire' ),
    path('',ArticlesListView.as_view() ,name='List_articles'),
    path('add-comment/<int:id>/', add_comment, name='add-comment'),
] 

accounts/urls.py
from django.urls import path

from .views import create_user, login_user, logout_view

app_name = 'accounts'

urlpatterns = [
    path('creation/', create_user, name='create'),
    path('login/', login_user, name='login'),
    path('logout/', logout_view, name='logout'),
]

blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path , include

urlpatterns = [
    path('account/',include('accounts.urls')),
    path('',include('Articles.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Articles/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Articles(models.Model):
    title = models.CharField(max_length=100,verbose_name='titre')
    sumary = models.CharField(max_length=200,verbose_name='Resume')
    date_pub = models.DateTimeField(null=True,default=timezone.now,verbose_name='Date de publication')
    content = models.TextField(default="Contenu par défaut",verbose_name='Contenu')
    cover = models.ImageField(upload_to='covers/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=False)
    CATEGORIE_CHOICES = [
        (1, 'Politique'),
        (2, 'Technologie'),
        (3, 'Sport'),
        (4, 'Voiture'),
        (5, 'Decouverte'),
        (6, 'Education')
    ]
    categorie= models.IntegerField(choices=CATEGORIE_CHOICES,null=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    content = models.TextField(verbose_name='contenu')
    created_at = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey(Articles, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.PROTECT, null=True, blank=False)

    def __str__(self):
        return f"{self.created_at}"

Articles/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Articles , Comment 

# class ArticlesForm(forms.Form) :
#     title = forms.CharField(min_length=2 , max_length=255)
#     sumary = forms.CharField(min_length=2 , max_length=255 ,required=False)
#     date_pub = forms.DateField(required=False)
#     content = forms.CharField(widget=forms.Textarea(attrs={'required':True}))


class ArticlesForm(forms.ModelForm) :
    cover = forms.ImageField(required=True)

    
    class Meta:
        model = Articles
        fields = ('title','sumary','date_pub','content','cover','categorie')
        widgets = {
            'title' : forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Titre'}),
            'sumary' : forms.TextInput(attrs={'class': 'form-control', 'placeholder':'resume'}),
            'date_pub' : forms.DateTimeInput(attrs={'class': 'form-control', 'placeholder':'Date de publication'}),
            'content' : forms.Textarea(attrs={'class' : 'form-control', 'placeholder':'contenu'}),
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('content', )
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control' , 'placeholder':'votre commentaire'})
        }

Articles/views.py
from django.http import HttpResponse 
from django.shortcuts import render , redirect , get_object_or_404
from django.urls import reverse , reverse_lazy
from .models import Articles
from .forms import ArticlesForm , CommentForm
from django.views.generic import ListView , CreateView , DeleteView , UpdateView , DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q

import logging

logger = logging.getLogger(__name__)


def home(request):
    return HttpResponse("hello words")

from django.views.generic import ListView
from .models import Articles

class ArticlesListView(ListView):
    model = Articles
    template_name = 'Articles/home.html'  # Chemin du template
    context_object_name = 'articles'      # Nom utilisé dans le template pour les articles
    

    def get_queryset(self):
        queryset = super().get_queryset()
        categorie = self.request.GET.get('categorie')
        query = self.request.GET.get('q')

        if categorie:
            queryset = queryset.filter(categorie=categorie)

        if query:
            queryset = queryset.filter(
                Q(title__icontains=query) | Q(sumary__icontains=query) | Q(content__icontains=query)
            )

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Ajouter des articles classés par catégorie au contexte
        context['articles_by_category'] = {
            'Politique': Articles.objects.filter(categorie=1),
            'Technologie': Articles.objects.filter(categorie=2),
            'Sport': Articles.objects.filter(categorie=3),
            'Voiture': Articles.objects.filter(categorie=4),
            'Decouverte': Articles.objects.filter(categorie=5),
            'Education': Articles.objects.filter(categorie=6),
        }
        
        return context


class ArticlesCreateView(LoginRequiredMixin, CreateView):
    model = Articles
    form_class = ArticlesForm
    template_name = 'Articles/formulaire.html'
    success_url = reverse_lazy('List_articles')

    def form_valid(self, form):
        # Associer l'utilisateur connecté à l'article avant de l'enregistrer
        form.instance.user = self.request.user
        return super().form_valid(form)
    
    def form_invalid(self, form):
        logger.error("Le formulaire est invalide : %s", form.errors)  # Log les erreurs de validation
        return super().form_invalid(form)

    
class ArticlesDeleteView(DeleteView):
    model = Articles
    template_name = 'Articles/delete_article.html'
    success_url = reverse_lazy('List_articles')


class ArticlesUpdateView(LoginRequiredMixin,UpdateView):
    model = Articles
    form_class = ArticlesForm
    template_name = 'Articles/update_article.html'
    success_url = reverse_lazy('List_articles')
    
class ArticlesDetailView(DetailView):
    model = Articles
    template_name = 'Articles/detail.html'
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context
    

def add_comment(request, id):

    if request.method == 'POST':
        article = Articles.objects.get(id=id)
        # initial = {'article': article}
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.owner = request.user
            comment.save()
        else:
            context = {
                'article': article,
                'form': form
            }
            return render(request, 'articles/article_detail.html', context)
    return redirect('detail_article', article.id)

# def List_articles(request):
#     articles = Articles.objects.all()
#     context = {
#         'articles' : articles
#     }
    
#     return render(request,'Articles/List.html',context)



# def formulaire(request):
#     if request.method == 'POST':
#         form = ArticlesForm(request.POST , files=request.FILES)
#         if form.is_valid():
#             # cleaned_data = form.cleaned_data
#             # article = Articles(**cleaned_data)
#             # article.title = cleaned_data['title']
#             # article.sumary = cleaned_data['sumary']
#             # article.date_pub = cleaned_data['date_pub']
#             # article.content = cleaned_data['content']
#             form.save()
#             return redirect(reverse('List_articles'))
#         else :
#             print(form.errors)
#     else :
#         form = ArticlesForm()
#     context  = {
#         'form': form
#     }
#     return render(request,'Articles/formulaire.html',context)


# def delete_article(request, article_id):
#     article = get_object_or_404(Articles, id=article_id)
#     if request.method == 'POST':
#         article.delete()
#         return redirect(reverse('List_articles'))
#     context = {
#         'article': article
#     }
#     return render(request, 'Articles/delete_article.html', context)


# def update_article(request, article_id):
#     article = get_object_or_404(Articles, id=article_id)

#     if request.method == 'POST':
#         form = ArticlesForm(request.POST, instance=article)
#         if form.is_valid():
#             form.save()
#             return redirect(reverse('List_articles'))
#     else:
#         form = ArticlesForm(instance=article)

#     context = {
#         'form': form,
#         'article': article
#     }
#     return render(request, 'Articles/update_article.html', context)
         

Articles/templates/Articles/Layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'articles/bootstrap.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Articles</title>
</head>
<body class="">
    {% include "Articles/nav_bar.html" %}
    {% block content %}
    {% endblock content %}
</body>
</html>

Articles/templates/Articles/List.html
{% extends "Articles/Layout.html" %}

{% block content %}
<div class="container mt-4">
    <div class="row d-flex flex-wrap">
        {% for article in articles %}
        <div class="col-md-3 mb-4 d-flex align-items-stretch"> <!-- Ajout de mb-4 pour espacer les cartes et align-items-stretch pour des hauteurs cohérentes -->
            <div class="card h-100 d-flex flex-column"> <!-- Ajout de h-100 pour uniformiser la hauteur des cartes -->
                <!-- Utilisation d'un wrapper pour contrôler la taille de l'image -->
                <div class="card-img-top-wrapper" style="height: 180px; overflow: hidden;">
                    <img src="{% if article.cover %}{{ article.cover.url }}{% endif %}" class="card-img-top" style="object-fit: cover; width: 100%; height: 100%;" alt="{{ article.title }}">
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title">{{ article.title }}</h5>
                    <p class="card-text">{{ article.sumary }}</p>
                    <a href="{% url 'detail_article' article.id %}" class="btn btn-success mt-auto">Détails</a> <!-- Utilisation de mt-auto pour placer le bouton en bas -->
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

Articles/templates/Articles/delete_article.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Supprimer l'Article</title>
    <!-- Lien vers le fichier CSS de Bootstrap -->
    <link rel="stylesheet" href="{% static 'artistes/bootstrap.css' %}">
</head>
<body class="container mt-5">

    <!-- Contenu principal -->
    <h1>Êtes-vous sûr de vouloir supprimer l'article : "{{ articles.title }}" ?</h1>
    
    <!-- Formulaire de confirmation de suppression -->
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="Supprimer" class="btn btn-danger">
        <a href="{% url 'List_articles' %}" class="btn btn-secondary">Annuler</a>
    </form>
    
</body>
</html>

Articles/templates/Articles/detail.html
{% extends "Articles/Layout.html" %}

{% block content %}
<div class="container mt-5">
    <!-- Détails de l'article -->
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h1 class="mb-4">Détails de l'Article : {{ article.title }}</h1>
            <div class="card mb-4">
                <div class="card-body">
                    <p><strong>ID :</strong> {{ article.id }}</p>
                    <p><strong>Titre :</strong> {{ article.title }}</p>
                    <p><strong>Résumé :</strong> {{ article.sumary }}</p>
                    <p><strong>Date de Publication :</strong> {{ article.date_pub }}</p>
                    {% if article.cover %}
                        <div class="my-3">
                            <img src="{{ article.cover.url }}" alt="{{ article.title }}" class="img-fluid rounded">
                        </div>
                    {% endif %}
                    <p><strong>Contenu :</strong> {{ article.content }}</p>
                </div>
            </div>
            
            <!-- Boutons Modifier et Supprimer pour l'utilisateur -->
            {% if user.is_authenticated and user == article.user %}
                <a href="{% url 'update_article' article.id %}" class="btn btn-info">Modifier</a>
                <a href="{% url 'delete_article' article.id %}" class="btn btn-danger">Supprimer</a>
            {% endif %}
        </div>
    </div>

    <!-- Formulaire d'ajout de commentaire -->
    {% if user.is_authenticated %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <form action="{% url 'add-comment' article.id %}" method="post" class="mb-4">
                {% csrf_token %}
                <div class="form-group">
                    {{ form }}
                </div>
                <button class="btn btn-primary mt-2">Enregistrer</button>
            </form>
        </div>
    </div>
    {% endif %}

    <!-- Affichage des commentaires -->
    {% for comment in article.comment_set.all %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card text-bg-light mb-3">
                <div class="card-header">{{ comment.owner.get_full_name }}</div>
                <div class="card-body">
                    <h5 class="card-title">{{ comment.created_at }}</h5>
                    <p class="card-text">{{ comment.content }}</p>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

Articles/templates/Articles/formulaire.html
{% extends "Articles/Layout.html" %}

{% block content %}
   <div class="container mt-5">
        <div class="row">
            <div class="col-md-8 offset-md-2">
          
                    <!-- Affichage des erreurs non liées à un champ spécifique -->
                    {% if form.errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for field, errors in form.errors.items %}
                                <li>{{ field }}: {{ errors }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    <form method="post" novalidate="novalidate" enctype="multipart/form-data" >
                        {% csrf_token %}
                        <div class="control-group">
                                <!-- Champ "Votre nom" -->
                                {{ form.title.label_tag }}
                                {{ form.title }}
                                <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <!-- Champ "Email" -->
                            {{ form.sumary.label_tag }}
                            {{ form.sumary }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <!-- Champ "Sujet" -->
                            {{ form.date_pub.label_tag }}
                            {{ form.date_pub }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <!-- Champ "Message" -->
                            {{ form.content.label_tag }}
                            {{ form.content }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <!-- Champ "Message" -->
                            {{ form.cover.label_tag }}
                            {{ form.cover }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="control-group">
                            <!-- Champ "Message" -->
                            {{ form.categorie.label_tag }}
                            {{ form.categorie }}
                            <p class="help-block text-danger"></p>
                        </div>
                        <div class="text-center">
                            <input type="submit" value="Enregistrer" class="btn btn-info">
                            <input type="reset" value="Annuler" class="btn btn-danger">
                        </div>
                    </form>
            </div>

        </div>
                      
                   
    </div>               
          
</div>
{% endblock content %}

Articles/templates/Articles/nav_bar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>NEWSROOM - Free Bootstrap Magazine Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="{% static 'articles/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet">   

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'articles/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'articles/style.css' %}" rel="stylesheet">
</head>

<body>
            <div class="container-fluid p-0 mb-3">
              <nav class="navbar navbar-expand-lg bg-light navbar-light py-2 py-lg-0 px-lg-5">
                  <a href="" class="navbar-brand d-block d-lg-none">
                      <h1 class="m-0 display-5 text-uppercase"><span class="text-primary">News</span>Room</h1>
                  </a>
                  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                      <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse justify-content-between px-0 px-lg-3" id="navbarCollapse">
                      <div class="navbar-nav mr-auto py-0">
                          <a href="{% url 'List_articles' %}" class="nav-item nav-link active">Home</a>
                          {% if user.is_authenticated %}
                            <a href="{% url 'formulaire' %}" class="nav-item nav-link">Single News</a>
                            <a href="{% url 'accounts:logout' %}" class="nav-item nav-link">Deconnexion</a>
                          {% else %}
                            <a href="{% url 'accounts:login' %}" class="nav-item nav-link">Connexion</a>
                          {% endif %}
                      </div>
                      <form method="GET" action="{% url 'List_articles' %}">
                          <div class="input-group ml-auto" style="width: 100%; max-width: 300px;">
                              <select name="categorie" class="form-control">
                                  <option value="">Toutes les catégories</option>
                                  <option value="1">Politique</option>
                                  <option value="2">Technologie</option>
                                  <option value="3">Sport</option>
                                  <option value="4">Voiture</option>
                                  <option value="5">Découverte</option>
                              </select>
                              <input type="text" name="q" class="form-control" placeholder="Keyword">
                              <div class="input-group-append">
                                  <button class="input-group-text text-secondary" type="submit">
                                      <i class="fa fa-search"></i>
                                  </button>
                              </div>
                          </div>
                      </form>
                      
                  </div>
              </nav>
          </div>
   <!-- JavaScript Libraries -->
   <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
   <script src="{% static 'articles/easing.min.js' %}"></script>
   <script src="{% static 'articles/owl.carousel.min.js' %}"></script>

   <!-- Contact Javascript File -->
   <script src="mail/jqBootstrapValidation.min.js"></script>
   <script src="mail/contact.js"></script>

   <!-- Template Javascript -->
   <script src="{% static 'articles/main.js' %}"></script>
</body>
</html>

Articles/templates/Articles/update_article.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'artistes/bootstrap.css' %} ">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier l'Article</title>
</head>
<body class="container">
    <h1>Modifier l'Article : {{ articles.title }}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Enregistrer" class="btn btn-primary">
        <a href="{% url 'List_articles' %}">Annuler</a>
    </form>
</body>
</html>